framework:
    messenger:

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        routing:
            # Route your messages to the transports
            'App\Messenger\Message\UserMessage': async