version: '3.5'
 
services:
  phpmyadmin:
     container_name: phpmyadmin
     image: phpmyadmin/phpmyadmin
     environment:
         PMA_HOST: ecommerce-mysql
     restart: always
     ports:
         - 9080:80
     networks:
       - ecommerce-network

  ecommerce: #Servicio que va a tener mi aplicación
   container_name: ecommerce #Nombre del servicio
   build:
     context: ./docker #Carpeta donde buscar Dockerfile
     args:
       UID: $U_ID
   volumes:
     - ./:/appdata/www #Todo lo que hay en la carpeta del proyecto lo va a mapear a www en el contenedor.
   ###> XDEBUG 3 ###
   # Use your client IP here
   # Linux: run "ip a | grep docker0"
   # Windows (with WSL2) and Mac: host.docker.internal
   environment:
     XDEBUG_CLIENT_HOST: 172.17.0.1
     XDEBUG_CLIENT_PORT: 9003
     PHP_IDE_CONFIG: serverName=ecommerce #Solo necesario en PHPStorm
   ports:
     - '1000:8000' #Redirección del puerto 1000 de mi máquina local al puerto 8000 del contenedor.
   networks:
     - ecommerce-network #Para que todos los servicios de la misma red se puedan ver entre ellos  
   depends_on:
      - ecommerce-postgres

  ecommerce-postgres:
    container_name: ecommerce-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres_symfony
    volumes:
      - ecommerce-pgsql-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  ecommerce-mysql:
    container_name: ecommerce-mysql
    image: mysql:8.0.26
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: mysql_ecommerce
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ecommerce-mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
 
  ecommerce-rabbit:
   container_name: ecommerce-rabbitmq
   image: rabbitmq:3-management-alpine
   ports:
     - '5672:5672'
     - '15672:15672'
   networks:
     - ecommerce-network
     
networks:
 ecommerce-network:

volumes:
  ecommerce-pgsql-data:
  ecommerce-mysql-data:
