messenger:
  path: /messenger
  controller: App\Controller\MessengerAction
  methods: [GET]

# USER ROUTES
register:
   path: /register/{id?}
   controller: App\Controller\UserController::register

login_check:
   path: /login-check

logout:
   path: /logout 

# PRODUCT ROUTES
newProduct:
   path: /new-product
   controller: App\Controller\ProductController::create

index:
   path: /
   controller: App\Controller\ProductController::index

manageProducts:
   path: /manage-products
   controller: App\Controller\ProductController::manage
   
editProduct:
   path: /product_edit/{id}
   controller: App\Controller\ProductController::create

removeProduct:
   path: /product_remove/{id}
   controller: App\Controller\ProductController::remove

productDetail:
   path: /product_detail/{id}/{img_id?}
   controller: App\Controller\ProductController::detail
   defaults:
      img_id: null

remove_image:
   path: /remove_image/{id}
   controller: App\Controller\ImageController::remove_image

set_default:
   path: /set_default/{id}
   controller: App\Controller\ImageController::set_default

select_main:
   path: /select_main/{img_id}
   controller: App\Controller\ProductController:select_main

# CATEGORY ROUTES
manageCategories:
   path: /manage-categories
   controller: App\Controller\CategoryController::manage

editCategory:
   path: /category_edit/{id}
   controller: App\Controller\CategoryController::edit

removeCategory:
   path: /category_remove/{id}
   controller: App\Controller\CategoryController::remove

showCategory:
   path: /show_cat/{id}
   controller: App\Controller\CategoryController::showCategory

# BRAND ROUTES
manageBrands:
   path: /manage-brands
   controller: App\Controller\BrandController::manage

editBrand:
   path: /brand_edit/{id}
   controller: App\Controller\BrandController::edit

removeBrand:
   path: /brand_remove/{id}
   controller: App\Controller\BrandController::remove

showBrand:
   path: /show_brand/{id}
   controller: App\Controller\BrandController::showBrand

# BASKET ROUTES 
basket:
   path: /basket/{id?}
   controller: App\Controller\BasketController::index

addToBasket:
   path: /addtobasket/{id}
   controller: App\Controller\BasketController::add

emptyBasket:
   path: /emptybasket
   controller: App\Controller\BasketController::emptyBasket

removeRow:
   path: /removeRow/{id}
   controller: App\Controller\BasketController::removeRow

basketUp:
   path: /basketup/{id}
   controller: App\Controller\BasketController::up

basketDown:
   path: /basketdown/{id}
   controller: App\Controller\BasketController::down

# ORDER ROUTES
make_order:
   path: /make_order/{id}
   controller: App\Controller\OrderController::makeOrder

orderConfirmation:
   path: /order_confirmation/{id}
   controller: App\Controller\OrderController::orderConfirmation

user_orders_index:
   path: /user_orders_index/{id}
   controller: App\Controller\OrderController::index

orderDetails:
   path: /order/{id}
   controller: App\Controller\OrderController::showDetails
