messenger:
  path: /messenger
  controller: App\Controller\MessengerAction
  methods: [GET]

# USER ROUTES
register:
   path: /register/{id?}
   controller: App\Controller\UserController::register

login_check:
   path: /login-check

logout:
   path: /logout 

# PRODUCT ROUTES
newProduct:
   path: /manage/product/create
   controller: App\Controller\ProductController::create

index:
   path: /
   controller: App\Controller\ProductController::index

manageProducts:
   path: /manage/product/manage
   controller: App\Controller\ProductController::manage
   
editProduct:
   path: /manage/product/edit/{id}
   controller: App\Controller\ProductController::create

updateCatalogue:
   path: /manage/product/cat/{id}/{cat}
   controller: App\Controller\ProductController::updateCatalogue

productDetail:
   path: /prod-detail/{id}/{img_id?}
   controller: App\Controller\ProductController::detail
   defaults:
      img_id: null

remove_image:
   path: /manage/product/image/remove/{id}
   controller: App\Controller\ImageController::remove_image

set_default:
   path: /manage/product/image/set_default/{id}
   controller: App\Controller\ImageController::set_default

# CATEGORY ROUTES
manageCategories:
   path: /manage/category
   controller: App\Controller\CategoryController::manage

editCategory:
   path: /manage/category/edit/{id}
   controller: App\Controller\CategoryController::edit

removeCategory:
   path: /manage/category/remove/{id}
   controller: App\Controller\CategoryController::remove

showCategory:
   path: /show_cat/{id}
   controller: App\Controller\CategoryController::showCategory

# BRAND ROUTES
manageBrands:
   path: /manage/brand/
   controller: App\Controller\BrandController::manage

editBrand:
   path: /brand/edit/{id}
   controller: App\Controller\BrandController::edit

removeBrand:
   path: /manage/brand/remove/{id}
   controller: App\Controller\BrandController::remove

showBrand:
   path: /show_brand/{id}
   controller: App\Controller\BrandController::showBrand

# BASKET ROUTES 

addToBasket:
   path: /basket/add/{id}
   controller: App\Controller\BasketController::add

emptyBasket:
   path: /basket/empty
   controller: App\Controller\BasketController::emptyBasket

removeRow:
   path: /basket/row/remove/{id}
   controller: App\Controller\BasketController::removeRow

basketUp:
   path: /basket/up/{id}
   controller: App\Controller\BasketController::up

basketDown:
   path: /basket/down/{id}
   controller: App\Controller\BasketController::down

basket:
   path: /basket/{id?}/{msg?}
   controller: App\Controller\BasketController::index

# ORDER ROUTES
make_order:
   path: /order/make/{id}
   controller: App\Controller\OrderController::makeOrder

makeOrderFromLogin:
   path: /order/makeFromLogin/{id}
   controller: App\Controller\OrderController::makeOrderFromLogin

orderConfirmation:
   path: /order/confirmation/{id}
   controller: App\Controller\OrderController::orderConfirmation

user_orders_index:
   path: /order/user/{id}
   controller: App\Controller\OrderController::userIndex

manageOrders:
   path: /manage/orders
   controller: App\Controller\OrderController::index

updateOrderStatus:
   path: /manage/order/status/{id}
   controller: App\Controller\OrderController::updateOrderStatus

orderDetails:
   path: /order/{id}
   controller: App\Controller\OrderController::showDetails

